// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArHaHos7WPYlZcV5AkvS9c_x30-BBqfnc',
    appId: '1:357225883169:web:1a5f6fa56bf5803acfa560',
    messagingSenderId: '357225883169',
    projectId: 'kazi-9a160',
    authDomain: 'kazi-9a160.firebaseapp.com',
    storageBucket: 'kazi-9a160.firebasestorage.app',
    measurementId: 'G-Y1B9715C1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6HcKC4dkxDcIDAVqMSd5cWSx1x4zkk44',
    appId: '1:357225883169:android:8604b267c4693070cfa560',
    messagingSenderId: '357225883169',
    projectId: 'kazi-9a160',
    storageBucket: 'kazi-9a160.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB79KUaiZ2foMiQ6nRjuBX-yu-djcT7wpc',
    appId: '1:357225883169:ios:e2e8cd85fe8eaeabcfa560',
    messagingSenderId: '357225883169',
    projectId: 'kazi-9a160',
    storageBucket: 'kazi-9a160.firebasestorage.app',
    iosBundleId: 'rw.ac.alu.kazi',
  );
}
